## -------------------------------------------------------
## VARIABLES - ENV
x-cms-admin-email: &cms-admin-email ${CMS_ADMIN_EMAIL}
x-cms-admin-password: &cms-admin-password ${CMS_ADMIN_PASSWORD}
x-cms-admin-token: &cms-admin-token ${CMS_ADMIN_TOKEN}
x-cms-secret: &cms-secret ${CMS_SECRET_KEY}
x-cms-public-url: &cms-public-url ${NEXT_PUBLIC_CMS_URL}
x-site-public-url: &site-public-url ${NEXT_PUBLIC_SITE_URL}
x-db-password: &db-password ${DATABASE_PASSWORD}
x-timezone: &timezone ${TIMEZONE}
## VARIABLES - EMAIL
x-cms-smtp-host: &cms-smtp-host ${CMS_SMTP_HOST}
x-cms-smtp-port: &cms-smtp-port ${CMS_SMTP_PORT}
x-cms-smtp-user: &cms-smtp-user ${CMS_SMTP_USER}
x-cms-smtp-password: &cms-smtp-password ${CMS_SMTP_PASSWORD}
x-cms-smtp-secure: &cms-smtp-secure ${CMS_SMTP_SECURE}
x-cms-smtp-ignore-tls: &cms-smtp-ignore-tls ${CMS_SMTP_IGNORE_TLS}
x-cms-smtp-name: &cms-smtp-name ${CMS_SMTP_NAME}
## VARIABLES - COMPOSE
x-db-name: &db-name "directus"
x-db-user: &db-user "directus"

## -------------------------------------------------------
services:
  ## -------------------------------------------------------
  ## DATABASE: POSTGRESQL
  db:
    container_name: dungeoncomic_db
    image: postgres:18.4
    networks:
      - dungeoncomic
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_USER: *db-user
      POSTGRES_DB: *db-name
      POSTGRES_PASSWORD: *db-password
      TZ: *timezone
      PGTZ: *timezone
      QUERY_LIMIT_MAX: -1
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: unless-stopped

  ## -------------------------------------------------------
  ## CACHE: REDIS
  cache:
    container_name: dungeoncomic_cache
    image: redis:8.8.0
    networks:
      - dungeoncomic
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: unless-stopped

  ## -------------------------------------------------------
  ## CMS: DIRECTUS
  cms:
    container_name: dungeoncomic_cms
    image: directus/directus:12.1.1
    ports:
      - 8055:8055
    networks:
      - dungeoncomic
    volumes:
      - uploads:/directus/uploads
      - templates:/directus/templates
      - ./schema.yaml:/directus/schema.yaml
    command: >
      sh -c "node cli.js bootstrap &&
            node cli.js schema apply --yes /directus/schema.yaml &&
            pm2-runtime start ecosystem.config.cjs"
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      # Directus - Settings
      SECRET: *cms-secret
      TZ: *timezone
      HEALTHCHECK_ENABLED: true
      HEALTHCHECK_NAMESPACE: directus:healthcheck
      HEALTHCHECK_SERVICES: database,redis,storage
      HEALTHCHECK_CACHE_TTL: 5m

      # Directus - Database
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: *db-name
      DB_USER: *db-user
      DB_PASSWORD: *db-password

      # Directus - Cache
      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      CACHE_STORE: redis
      REDIS: redis://cache:6379

      # Directus - Admin
      ADMIN_EMAIL: *cms-admin-email
      ADMIN_PASSWORD: *cms-admin-password
      ADMIN_TOKEN: *cms-admin-token
      PUBLIC_URL: *cms-public-url

      # Directus - Storage
      STORAGE_LOCATIONS: local
      STORAGE_LOCAL_DRIVER: local
      STORAGE_LOCAL_ROOT: /directus/uploads

      # Directus - Token Security
      ACCESS_TOKEN_TTL: 14d
      SESSION_COOKIE_TTL: 14d
      REFRESH_TOKEN_TTL: 14d

      # DIRECTUS - EMAIL
      # - https://directus.com/docs/configuration/email
      EMAIL_VERIFY_SETUP: true
      EMAIL_TRANSPORT: smtp
      EMAIL_FROM: *cms-smtp-user
      EMAIL_SMTP_HOST: *cms-smtp-host
      EMAIL_SMTP_PORT: *cms-smtp-port
      EMAIL_SMTP_USER: *cms-smtp-user
      EMAIL_SMTP_PASSWORD: *cms-smtp-password
      EMAIL_SMTP_SECURE: *cms-smtp-secure
      EMAIL_SMTP_IGNORE_TLS: *cms-smtp-ignore-tls
      EMAIL_SMTP_NAME: *cms-smtp-name

      # DIRECTUS - URL SECURITY
      CORS_ENABLED: "true"
      CORS_ORIGIN: &site-public-url
      USER_REGISTER_URL_ALLOW_LIST: &site-public-url
      PASSWORD_RESET_URL_ALLOW_LIST: &site-public-url

      SERVE_APP: ${CMS_SERVE_APP}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "[ $$(wget -q -O - http://0.0.0.0:8055/server/ping) = 'pong' ]",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
  ## -------------------------------------------------------
  ## FRONTEND: NEXT.JS
  frontend:
    container_name: dungeoncomic_frontend
    image: dungeoncomic/next.js:16.2.10
    depends_on:
      cms:
        condition: service_healthy
    build:
      context: .
      args:
        # CMS_DOCKER_URL is specifically for when the Next.js container needs to talk to the directus container
        CMS_DOCKER_URL: http://dungeoncomic_cms:8055
    environment:
      # NEXT_PUBLIC_CMS_URL is the public-facing website URL
      NEXT_PUBLIC_CMS_URL: ${NEXT_PUBLIC_CMS_URL}
    ports:
      - 3000:3000
    networks:
      - dungeoncomic

## -------------------------------------------------------
volumes:
  cache:
    name: dungeoncomic_cache
  db:
    name: dungeoncomic_db
  uploads:
    name: dungeoncomic_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./cms/uploads
  templates:
    name: dungeoncomic_templates
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./cms/templates

## -------------------------------------------------------
networks:
  dungeoncomic:
    name: dungeoncomic
    driver: bridge
