## -------------------------------------------------------
## VARIABLES - ENV
x-cms-admin-email: &cms-admin-email ${CMS_ADMIN_EMAIL}
x-cms-admin-password: &cms-admin-password ${CMS_ADMIN_PASSWORD}
x-cms-admin-token: &cms-admin-token ${CMS_ADMIN_TOKEN}
x-cms-secret: &cms-secret ${CMS_SECRET_KEY}
x-cms-public-url: &cms-public-url ${NEXT_PUBLIC_CMS_URL}
x-db-password: &db-password ${DATABASE_PASSWORD}
x-timezone: &timezone ${TIMEZONE}
## VARIABLES - COMPOSE
x-db-name: &db-name "directus"
x-db-user: &db-user "directus"

## -------------------------------------------------------
services:
  ## -------------------------------------------------------
  ## DATABASE: POSTGRESQL
  db:
    container_name: dcc_db
    image: postgres:18.4
    networks:
      - dcc
    volumes:
      - db:/var/lib/postgresql
    environment:
      POSTGRES_USER: *db-user
      POSTGRES_DB: *db-name
      POSTGRES_PASSWORD: *db-password
      TZ: *timezone
      PGTZ: *timezone
      QUERY_LIMIT_MAX: -1
    healthcheck:
      test: ["CMD", "pg_isready", "--host=localhost", "--username=directus"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: unless-stopped

  ## -------------------------------------------------------
  ## CACHE: REDIS
  cache:
    container_name: dcc_cache
    image: redis:8.8.0
    networks:
      - dcc
    volumes:
      - cache:/data
    healthcheck:
      test: ["CMD-SHELL", "[ $$(redis-cli ping) = 'PONG' ]"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_interval: 5s
      start_period: 30s
    restart: unless-stopped

  ## -------------------------------------------------------
  ## CMS: DIRECTUS
  cms:
    container_name: dcc_cms
    image: directus/directus:12.1.1
    ports:
      - 8055:8055
    networks:
      - dcc
    volumes:
      - uploads:/directus/uploads
      - extensions:/directus/extensions
      - ./schema.yaml:/directus/schema.yaml

    command: >
      sh -c "node cli.js bootstrap &&
            node cli.js schema apply --yes /directus/schema.yaml &&
            pm2-runtime start ecosystem.config.cjs"
    depends_on:
      cache:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      # Directus - Settings
      SECRET: *cms-secret
      TZ: *timezone
      HEALTHCHECK_ENABLED: true
      HEALTHCHECK_NAMESPACE: directus:healthcheck
      HEALTHCHECK_SERVICES: database,redis,storage
      HEALTHCHECK_CACHE_TTL: 5m

      # Directus - Database
      DB_CLIENT: pg
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: *db-name
      DB_USER: *db-user
      DB_PASSWORD: *db-password

      # Directus - Cache
      CACHE_ENABLED: true
      CACHE_AUTO_PURGE: true
      CACHE_STORE: redis
      REDIS: redis://cache:6379

      # Directus - Admin
      ADMIN_EMAIL: *cms-admin-email
      ADMIN_PASSWORD: *cms-admin-password
      ADMIN_TOKEN: *cms-admin-token
      PUBLIC_URL: *cms-public-url

      # Directus - Storage
      STORAGE_LOCATIONS: local
      STORAGE_LOCAL_DRIVER: local
      STORAGE_LOCAL_ROOT: /directus/uploads

      # DIRECTUS - EMAIL
      EMAIL_VERIFY_SETUP: false
      # - Directus emails are not technically required for our setup
      #   since you would only use it to reset your own password
      # - https://directus.com/docs/configuration/email
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "[ $$(wget -q -O - http://0.0.0.0:8055/server/ping) = 'pong' ]",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
  ## -------------------------------------------------------
  ## FRONTEND: NEXT.JS
  frontend:
    container_name: dcc_frontend
    image: next.js:16.2.10
    depends_on:
      cms:
        condition: service_healthy
    build:
      context: .
      args:
        # CMS_DOCKER_URL is specifically for when the Next.js container needs to talk to the directus container
        CMS_DOCKER_URL: http://dcc_cms:8055
    environment:
      NEXT_PUBLIC_CMS_URL: ${NEXT_PUBLIC_CMS_URL}
    ports:
      - 3000:3000
    networks:
      - dcc

## -------------------------------------------------------
volumes:
  cache:
    name: dcc_cache
  db:
    name: dcc_db
  uploads:
    name: dcc_uploads
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./cms/uploads
  extensions:
    name: dcc_extensions

## -------------------------------------------------------
networks:
  dcc:
    name: dcc
    driver: bridge
